http:
  routers:
    truenas:
      rule: "Host(`truenas.noassl.at`)"
      entryPoints: "websecure"
  services:
    truenas:
      loadBalancer:
        servers:
          - url: "http://192.168.0.52"