services:
  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - exporter
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  exporter:
    build:
      context: ./exporter
      dockerfile: Dockerfile
    volumes:
      - exports:/exports
    env_file:
      - .env
    labels:
      ofelia.enabled: "true"
      ofelia.job-run.exporter.schedule: "@midnight"

  analyzer:
    build:
      context: ./analyzer
      dockerfile: Dockerfile
    volumes:
      - exports:/exports
      - reports:/reports
    labels:
      ofelia.enabled: "true"
      ofelia.job-run.analyzer.schedule: "@midnight"

  webhost:
    image: nginx:alpine
    volumes:
      - reports:/usr/share/nginx/html
    labels:
      traefik.enable: true
      traefik.http.routers.discord-analytics.rule: "Host(`discord-analytics.noassl.at`)"
      traefik.http.routers.discord-analytics.entryPoints: "websecure"
      traefik.http.routers.discord-analytics.tls: true
      traefik.http.routers.discord-analytics.middlewares: "discord-analytics-auth"
      traefik.http.middlewares.discord-analytics-auth.basicauth.users: "user:$$2y$$05$$KAs4e4zflSuJ/dtWcSvZO.Dh0hrpVmJzoAb8x19QQSjrn.I7Kb9Pa"

    environment:
      NGINX_HOST: "discord-analytics.noassl.at"
    networks:
      - traefik

volumes:
  reports:
  exports:

networks:
  traefik:
    external: true
