services:
  scheduler:
    image: mcuadros/ofelia:latest
    container_name: "discord-analytics_scheduler"
    depends_on:
      - exporter
      - analyzer
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.save-folder: "/var/log/ofelia"

  exporter:
    container_name: "discord-analytics_exporter"
    build:
      context: ./exporter
      dockerfile: Dockerfile
    volumes:
      - exports:/exports
      - /var/log/discord-analytics/exporter.log:/var/log/discord-analytics/exporter.log
    env_file:
      - .env
    labels:
      ofelia.enabled: true
      ofelia.job-run.discord-analytics-exporter.container: "discord-analytics_exporter"
      ofelia.job-run.discord-analytics-exporter.schedule: "0 0 * * 1" # Jeden Montag um 0000

  analyzer:
    container_name: "discord-analytics_analyzer"
    build:
      context: ./analyzer
      dockerfile: Dockerfile
    volumes:
      - exports:/exports
      - reports:/reports
      - /var/log/discord-analytics/analyzer.log:/var/log/discord-analytics/analyzer.log
    labels:
      ofelia.enabled: true
      ofelia.job-run.discord-analytics-analyzer.container: "discord-analytics_exporter"
      ofelia.job-run.discord-analytics-analyzer.schedule: "0 1 * * 1" # Jeden Montag um 0100

  webhost:
    container_name: "discord-analytics_webhost"
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - reports:/usr/share/nginx/html
    environment:
      NGINX_HOST: "discord-analytics.noassl.at"
    labels:
      traefik.enable: true
      traefik.http.routers.discord-analytics.rule: "Host(`discord-analytics.noassl.at`)"
      traefik.http.routers.discord-analytics.entryPoints: "websecure"
      traefik.http.routers.discord-analytics.middlewares: "discord-analytics-auth"
      traefik.http.middlewares.discord-analytics-auth.basicauth.users: "user:$$2y$$05$$KAs4e4zflSuJ/dtWcSvZO.Dh0hrpVmJzoAb8x19QQSjrn.I7Kb9Pa"
    networks:
      - traefik

volumes:
  reports:
  exports:

networks:
  traefik:
    external: true
