services:
  scheduler:
    container_name: "discord-analytics_scheduler"
    build:
      context: ./scheduler
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log/discord-analytics.log:/var/log/cron.log
      - .:/app

  exporter:
    container_name: "discord-analytics_exporter"
    build:
      context: ./exporter
      dockerfile: Dockerfile
    volumes:
      - exports:/exports
    env_file:
      - .env

  analyzer:
    container_name: "discord-analytics_analyzer"
    build:
      context: ./analyzer
      dockerfile: Dockerfile
    volumes:
      - exports:/exports
      - reports:/reports

  webhost:
    container_name: "discord-analytics_webhost"
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - reports:/usr/share/nginx/html
    environment:
      NGINX_HOST: "discord-analytics.noassl.at"
    labels:
      traefik.enable: true
      traefik.http.routers.discord-analytics.rule: "Host(`discord-analytics.noassl.at`)"
      traefik.http.routers.discord-analytics.entryPoints: "websecure"
      traefik.http.routers.discord-analytics.middlewares: "discord-analytics-auth"
      traefik.http.middlewares.discord-analytics-auth.basicauth.users: "user:$$2y$$05$$KAs4e4zflSuJ/dtWcSvZO.Dh0hrpVmJzoAb8x19QQSjrn.I7Kb9Pa"
    networks:
      - traefik

volumes:
  reports:
  exports:

networks:
  traefik:
    external: true
