services:
  crafty:
    container_name: crafty
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    environment:
        TZ: Europe/Vienna
    ports:
        - "8000:8000" # HTTP (Crafty-Interface)
        - "8443:8443" # HTTPS (Crafty-Interface)
        # - "8123:8123" # DYNMAP (wos is dynmap)
        # - "19132:19132/udp" # BEDROCK (wer spüt des)
        - "25500-25600:25500-25600" # MC SERVER PORT RANGE
    volumes:
        - ./data/backups:/crafty/backups
        - ./data/logs:/crafty/logs
        - ./data/servers:/crafty/servers
        - ./data/config:/crafty/app/config
        - ./data/import:/crafty/import
    labels:
        com.centurylinklabs.watchtower.enable: true
