services:
  rustdesk-server:
    image: rustdesk/rustdesk-server-s6:latest
    container_name: rustdesk-server
    restart: unless-stopped
    environment:
      RELAY: "fernwartung.noassl.at:21117"
      TZ: "Europe/Vienna"
    ports:
      - "21115:21115/tcp"
      - "21116:21116/tcp"
      - "21117:21117/tcp"
      - "21118:21118/tcp"
      - "21119:21119/tcp"
      - "21116:21116/udp"
    volumes:
      - ./data:/data
    networks:
      - traefik

networks:
  traefik:
    external: true
