services:
  rustdesk-server:
    image: rustdesk/rustdesk-server-s6:latest
    container_name: rustdesk-server
    restart: unless-stopped
    environment:
      RELAY: "fernwartung.noassl.at:21117"
      TZ: "Europe/Vienna"
    volumes:
      - ./data:/data
    networks:
      - traefik
    labels:
      - traefik.enable=true
      ## Configure Rustdesk TCP
      - traefik.tcp.routers.rustdesk-rd5.entrypoints=rd5-tcp
      - traefik.tcp.routers.rustdesk-rd5.rule=HostSNI(`*`)
      - traefik.tcp.routers.rustdesk-rd5.service=rustdesk-rd5
      - traefik.tcp.services.rustdesk-rd5.loadbalancer.server.port=21115
      - traefik.tcp.routers.rustdesk-rd5.tls=false
      - traefik.tcp.routers.rustdesk-rd5.tls.passthrough=true

      - traefik.tcp.routers.rustdesk-rd6.entrypoints=rd6-tcp
      - traefik.tcp.routers.rustdesk-rd6.rule=HostSNI(`*`)
      - traefik.tcp.routers.rustdesk-rd6.service=rustdesk-rd6
      - traefik.tcp.services.rustdesk-rd6.loadbalancer.server.port=21116
      - traefik.tcp.routers.rustdesk-rd6.tls=false
      - traefik.tcp.routers.rustdesk-rd6.tls.passthrough=true

      - traefik.tcp.routers.rustdesk-rd7.entrypoints=rd7-tcp
      - traefik.tcp.routers.rustdesk-rd7.rule=HostSNI(`*`)
      - traefik.tcp.routers.rustdesk-rd7.service=rustdesk-rd7
      - traefik.tcp.services.rustdesk-rd7.loadbalancer.server.port=21117
      - traefik.tcp.routers.rustdesk-rd7.tls=false
      - traefik.tcp.routers.rustdesk-rd7.tls.passthrough=true

      - traefik.tcp.routers.rustdesk-rd8.entrypoints=rd8-tcp
      - traefik.tcp.routers.rustdesk-rd8.rule=HostSNI(`*`)
      - traefik.tcp.routers.rustdesk-rd8.service=rustdesk-rd8
      - traefik.tcp.services.rustdesk-rd8.loadbalancer.server.port=21118
      - traefik.tcp.routers.rustdesk-rd8.tls=false
      - traefik.tcp.routers.rustdesk-rd8.tls.passthrough=true

      - traefik.tcp.routers.rustdesk-rd9.entrypoints=rd9-tcp
      - traefik.tcp.routers.rustdesk-rd9.rule=HostSNI(`*`)
      - traefik.tcp.routers.rustdesk-rd9.service=rustdesk-rd9
      - traefik.tcp.services.rustdesk-rd9.loadbalancer.server.port=21119
      - traefik.tcp.routers.rustdesk-rd9.tls=false
      - traefik.tcp.routers.rustdesk-rd9.tls.passthrough=true

      ## Configure Rustdesk UDP
      - traefik.udp.routers.rustdesk-rd6.entrypoints=rd6-udp
      - traefik.udp.routers.rustdesk-rd6.service=rustdesk-rd6
      - traefik.udp.services.rustdesk-rd6.loadbalancer.server.port=21116

networks:
  traefik:
    external: true
