volumes:
  data:
  extensions:

services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - ./data:/var/www/FreshRSS/data
      - ./extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: Europe/Vienna
      CRON_MIN: '3,33'
      SERVER_DNS: freshrss.noassl.at
    labels:
      traefik.enable: true
      traefik.http.routers.freshrss.rule: "Host(`freshrss.noassl.at`)"
      traefik.http.routers.freshrss.entryPoints: "websecure"
      com.centurylinklabs.watchtower.enable: true

networks:
  default:
    name: traefik
    external: true
