# yaml-language-server: $schema=https://creativeprojects.github.io/resticprofile/jsonschema/config-1.json

version: "1"

includes:
    - "profiles/*.yaml"

#  Anchor for scheduling defaults
schedule-base: &schedule-base
    schedule: daily
    schedule-log: "/var/log/resticprofile/{{ .Profile.Name }}.log"
    schedule-permission: system
    schedule-lock-wait: "15m"

# Base profile that enables default schedule for all tasks
schedule-all:
    inherit: "schedule-cleanup"
    backup:
        <<: *schedule-base
        tag:
            - "resticprofile.timer"
    copy:
        <<: *schedule-base

# Base profile that enables default schedule for `forget` and `prune`
schedule-cleanup:
    forget:
        <<: *schedule-base
        keep-daily: 14
        keep-weekly: 4
        keep-monthly: 6
        keep-yearly: 3
        tag:
            - "resticprofile.timer"
        group-by: "paths"
    prune:
        <<: *schedule-base
        schedule: weekly
