services:
  NikeBotv2:
    image: ghcr.io/noassl/nikebotv2:main
    volumes:
      - ./config.json:/app/config.json
    env_file:
      - .env
    restart: unless-stopped
    container_name: "NikeBotv2"
    labels:
      com.centurylinklabs.watchtower.enable: true
